baseURL = 'http://ic-compendium.s3-website-us-east-1.amazonaws.com/'
languageCode = 'en-us'
title = 'IdeaCrew Compendium'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[params]
offlineSearch = true
