baseURL = 'https://compendium.docs.ideacrew.com/'
languageCode = 'en-us'
title = 'IdeaCrew Compendium'
relativeURLs = true
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[params]
offlineSearch = true
